apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patchesStrategicMerge:
  - provider.yml

secretGenerator:
  - name: gcp-secret
    options:
      disableNameSuffixHash: true
    files:
      - gcp-json
