# Establish relationships between the ServiceAccount resources needed if names
# are changed (e.g. via the utilities/unique-service-account.yml patch).
apiVersion: builtin
nameReference:
  - kind: ServiceAccount
    fieldSpecs:
      - kind: ClusterRoleBinding
        path: subjects/name
      - kind: SpinnakerService
        path: spec/spinnakerConfig/service-settings/clouddriver/kubernetes/serviceAccountName
  - kind: ClusterRole
    fieldSpecs:
      - kind: ClusterRoleBinding
        path: roleRef/name
